# Generated by Django 5.0 on 2024-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=5)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
