# Generated by Django 5.0 on 2024-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_session_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default='knead.fiord', max_length=100),
            preserve_default=False,
        ),
    ]
