# Generated by Django 5.0 on 2024-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_comment_name_comment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='media_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
