# Generated by Django 5.0 on 2024-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_customadmin_media_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
