# Generated by Django 5.0.6 on 2024-07-19 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "video_app",
            "0004_post_session_remove_media_class_associated_comment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="post_associated",
        ),
        migrations.AddField(
            model_name="media",
            name="session_associated",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="video_app.session",
            ),
        ),
    ]
