# Generated by Django 5.1 on 2024-09-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_comment_is_admin_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='StudentMediaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_graph', models.BooleanField(default=False)),
                ('liked_eye', models.BooleanField(default=False)),
                ('liked_read', models.BooleanField(default=False)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interactions', to='video_app.media')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_interactions', to='video_app.student')),
            ],
            options={
                'unique_together': {('student', 'media')},
            },
        ),
    ]
