# Generated by Django 5.1 on 2024-09-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_alter_media_options_studentmediainteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='password',
        ),
    ]
