# Generated by Django 5.0 on 2024-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_comment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='character_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
