# Generated by Django 5.0.6 on 2024-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0008_alter_media_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("image", "Image"),
                    ("comment", "Comment"),
                ],
                max_length=10,
            ),
        ),
    ]
