# Generated by Django 5.0.6 on 2024-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0009_media_likes_alter_media_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(default=1, upload_to="media_files/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="media",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=models.FileField(upload_to="media_files/"),
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=models.FileField(upload_to="media_files/"),
            ),
        ),
    ]
