# Generated by Django 5.0.6 on 2024-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0010_media_file_alter_media_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="file",
        ),
        migrations.AlterField(
            model_name="media",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="media",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos"),
        ),
    ]
