# Generated by Django 5.1.1 on 2024-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0012_session_character_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='graph_tag',
            field=models.CharField(blank=True, choices=[('box', 'Box Plot'), ('histogram', 'Histogram'), ('comparison', 'Comparison')], max_length=50, null=True),
        ),
    ]
