# Generated by Django 5.1.1 on 2024-10-30 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0013_comment_admin_avatar_alter_media_graph_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='studentmediainteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmediainteraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['session', '-uploaded_at'], name='video_app_m_session_042df8_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='video_app_m_media_t_8ddd46_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['graph_tag'], name='video_app_m_graph_t_0ef493_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['variable_tag'], name='video_app_m_variabl_ebb409_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmediainteraction',
            index=models.Index(fields=['student', 'media'], name='video_app_s_student_274bc3_idx'),
        ),
    ]
