# Generated by Django 5.1.1 on 2024-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0015_media_posted_by_admin_media_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadmin',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
