# Generated by Django 5.0.6 on 2024-07-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0015_remove_comment_content_remove_comment_post_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="media",
            name="tag",
            field=models.CharField(
                choices=[
                    ("education", "Education"),
                    ("announcement", "Announcement"),
                    ("discussion", "Discussion"),
                    ("other", "Other"),
                ],
                default="education",
                max_length=50,
            ),
        ),
    ]
