# Generated by Django 5.1.1 on 2024-12-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0016_customadmin_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='variable_tag',
            field=models.CharField(blank=True, choices=[('gender', 'Gender'), ('languages', 'Languages'), ('handedness', 'Handedness'), ('eye_color', 'Eye Color'), ('hair_color', 'Hair Color'), ('hair_type', 'Hair Type'), ('height', 'Height'), ('left_foot_length', 'Left Foot Length'), ('right_foot_length', 'Right Foot Length'), ('longer_foot', 'Longer Foot'), ('index_finger', 'Index Finger'), ('ring_finger', 'Ring Finger'), ('longer_finger', 'Longer Finger'), ('arm_span', 'Arm Span'), ('travel_method', 'Travel Method to School'), ('bed_time', 'Bed Time'), ('wake_time', 'Wake Time'), ('sport_activity', 'Sport or Activity'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('snapchat', 'Snapchat'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('twitch', 'Twitch'), ('pinterest', 'Pinterest'), ('bereal', 'BeReal'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord'), ('screen_time', 'Screen Time After School'), ('pineapple_pizza', 'Pineapple on Pizza'), ('ice_cream', 'Ice Cream'), ('cats_or_dogs', 'Cats or Dogs'), ('happiness', 'Happiness'), ('climate_change', 'Climate Change'), ('reaction_time', 'Reaction Time'), ('memory_test', 'Memory Test'), ('sleep_total', 'Sleep Total'), ('time_to_school', 'Time to School')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
