# Generated by Django 5.0.6 on 2024-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0016_delete_post_media_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="created_by",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
