# Generated by Django 5.0.6 on 2024-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0018_alter_session_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
