# Generated by Django 5.1.1 on 2024-12-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0018_session_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='project_group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
