# Generated by Django 5.0.6 on 2024-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0019_alter_session_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
