# Generated by Django 5.0 on 2024-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0020_comment_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='files_links',
        ),
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.AddField(
            model_name='session',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
