# Generated by Django 5.1.1 on 2024-12-16 16:52

from django.db import migrations

def update_modules(apps, schema_editor):
    Session = apps.get_model('video_app', 'Session')
    # Session.objects.filter(module__isnull=True).update(module='3')
    # Or if you want to update all records regardless:
    Session.objects.all().update(module='3')

class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0020_media_is_project_media_project_images'),
    ]

    operations = [
        migrations.RunPython(update_modules),
    ]
