# Generated by Django 5.0 on 2024-09-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0023_alter_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='likes',
            new_name='graph_likes',
        ),
        migrations.AddField(
            model_name='media',
            name='eye_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='read_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
