# Generated by Django 5.0 on 2024-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0026_media_is_graph_alter_media_graph_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='graph_tag',
            field=models.CharField(blank=True, choices=[('bar', 'Bar Chart'), ('line', 'Line Graph'), ('pie', 'Pie Chart'), ('box', 'Box Plot'), ('histogram', 'Histogram'), ('comparison', 'Comparison')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='variable_tag',
            field=models.CharField(blank=True, choices=[('gender', 'Gender'), ('languages', 'Languages'), ('handedness', 'Handedness'), ('eye_color', 'Eye Color'), ('hair_color', 'Hair Color'), ('hair_type', 'Hair Type'), ('height', 'Height'), ('left_foot_length', 'Left Foot Length'), ('right_foot_length', 'Right Foot Length'), ('longer_foot', 'Longer Foot'), ('index_finger', 'Index Finger'), ('ring_finger', 'Ring Finger'), ('longer_finger', 'Longer Finger'), ('arm_span', 'Arm Span'), ('travel_method', 'Travel Method to School'), ('bed_time', 'Bed Time'), ('wake_time', 'Wake Time'), ('sport_activity', 'Sport or Activity'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('snapchat', 'Snapchat'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('twitch', 'Twitch'), ('pinterest', 'Pinterest'), ('bereal', 'BeReal'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord'), ('screen_time', 'Screen Time After School'), ('pineapple_pizza', 'Pineapple on Pizza'), ('ice_cream', 'Ice Cream'), ('cats_or_dogs', 'Cats or Dogs'), ('happiness', 'Happiness'), ('climate_change', 'Climate Change'), ('reaction_time', 'Reaction Time'), ('memory_test', 'Memory Test')], max_length=50, null=True),
        ),
    ]
