# Generated by Django 5.0 on 2024-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0027_alter_media_graph_tag_alter_media_variable_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='submitted_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
