# Generated by Django 5.0 on 2024-09-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0028_media_submitted_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
